#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    region: region-1
#    service-url:
#      zone1: http://localhost:8999/eureka/
#      zone2: http://127.0.0.1:9000/eureka/
#    availability-zones:
#      region-1: zone1,zone2
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    region: region-1
#    service-url:
#      zone1: http://localhost:8999/eureka/
#      zone2: http://127.0.0.1:9000/eureka/
#    availability-zones:
#      zone1: zone1
#      zone2: zone2

spring:
  application:
    name: eureka